import React from 'react';
import {
    DollarSign,
    Eye,
    LayoutDashboard,
    ShoppingCart,
    History,
    Settings,
    Bell,
    Menu,
    SlidersHorizontal,
    UploadCloud,
    Receipt,
    Send,
    Plus,
    Minus,
    ChevronDown,
    Search,
    Calendar,
    Download,
    CheckCircle,
    MoreVertical,
    Printer,
    Play,
    Truck,
    PackageCheck,
    FileText,
    ScrollText,
    Check,
    Ban,
    Info,
    Save,
    Trash2,
    AlertTriangle,
    Wallet,
    BadgeDollarSign,
    Image,
    Layers,
    Grid3X3,
    Scan,
    Square,
    Link,
    X,
    ArrowRight,
    Phone,
    IdCard
} from 'lucide-react';

export const Icons = {
    DollarSign: DollarSign,
    Eye: Eye,
    Dashboard: LayoutDashboard,
    Cart: ShoppingCart,
    History: History,
    Settings: Settings,
    Bell: Bell,
    Menu: Menu,
    Tune: SlidersHorizontal,
    Upload: UploadCloud,
    Receipt: Receipt,
    Send: Send,
    Plus: Plus,
    Minus: Minus,
    ChevronDown: ChevronDown,
    Search: Search,
    Calendar: Calendar,
    Download: Download,
    CheckCircle: CheckCircle,
    MoreVertical: MoreVertical,
    Visibility: Eye,
    Print: Printer,
    Play: Play,
    Truck: Truck,
    PackageCheck: PackageCheck,
    Description: FileText,
    ReceiptLong: ScrollText,
    Check: Check,
    Block: Ban,
    Info: Info,
    Save: Save,
    Trash: Trash2,
    Alert: AlertTriangle,
    Wallet: Wallet,
    CurrencyExchange: BadgeDollarSign,
    Texture: Image,
    Layers: Layers,
    Grid: Grid3X3,
    Scanner: Scan,
    Panel: Square,
    Close: X,
    Link: Link,
    ArrowRight: ArrowRight,
    Phone: Phone,
    IdCard: IdCard,
    ExternalLink: Link,
    FileText: FileText
};
